### ISSUE TITLE
main branch empty and is set to default

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#1]
when you view this repo it appears empty as the main branch is set to the default and is not used.

I would suggest you change the default branch in the repo settings to point at your MOODLE_401_STABLE branch and delete the main branch to make it easier for people to see - alternatively you could also put a readme file in the main branch that explains which branches are active.

**Comment by cperves** [comment]
Hello,
I set the default branch to MOODLE_401_STABLE and put a README/md file into main branch
Thank you for these suggestions
