### ISSUE TITLE
Error when Inserting Image on TinyMCE editor Moodle 4.2.7

### ISSUE THREAD

**Issue by toyinal1200** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#11]
Error when Insert Image is clicked. Im on Moodle version 4.2.7 with installed Chemical substance tiny_molstructure version 1.0.4 dated 2024052100 on Tiny MCE editor
 I think the culprit is the line ? of unknownfile: call to core_component::classloader()
`line 41 of /lib/editor/tiny/plugins/molstructure/classes/external/image_generator.php: Error thrown
* line 147 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()`
Thanks

**Comment by cperves** [comment]
Hello,
according to the error you encountered you'd better take the 2.0.0 version (2024032502 created for 4.3 moodle version)
I'll try to make a unique version in the next 2 weeks

**Comment by cperves** [comment]
I made a new 2.0.1 tag and push it on moodle.org
Can you confirm in return if you arror is solved by this plugin version?
Thanks

**Comment by toyinal1200** [comment]
Tested working on Moodle 4.2.7
Cheers
Thanks

**Comment by cperves** [comment]
Wonderfull
