### ISSUE TITLE
missing validate_context check in webservice function

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#2]
this function needs a validate_context call:
https://github.com/Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure/blob/MOODLE_401_STABLE/classes/external/image_generator.php#L59

more info this here:
https://moodledev.io/docs/apis/subsystems/external/writing-a-service#context-and-capability-checks

**Comment by cperves** [comment]
Thank you for the link
