### ISSUE TITLE
mixed docs on itemid - is it an int or a string?

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#3]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure/blob/MOODLE_401_STABLE/classes/external/image_generator.php#L59

the docs and webservice validation function state it's an int, but the execute seems to require a string?

**Comment by cperves** [comment]
corrected in #2 (I forgot to push before, sorry)
