### ISSUE TITLE
does the return param need to be PARAM_RAW?

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#4]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure/blob/MOODLE_401_STABLE/classes/external/image_generator.php#L107

might be able to use PARAM_TEXT or something else there.

**Comment by cperves** [comment]
I'm going to  try PARAM_TEXT but initially I choose PARAM_RAW to prevent string to be cleaned by moodle
What do you think about that?

**Comment by cperves** [comment]
since PARAM_RAW "specifies a parameter that is not cleaned/processed in any way except the discarding of the invalid utf-8 characters", I prefer letting this because the data transmitted are imageDataUrl type

**Comment by danmarsden** [comment]
Isn't that just a url and not an image?

**Comment by cperves** [comment]
No this an ImageDataUrl string

**Comment by cperves** [comment]
generated by chemDodle lib

**Comment by danmarsden** [comment]
just looks like it's returning a url to me - not an actual image - eg:
https://github.com/Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure/blob/MOODLE_401_STABLE/classes/external/image_generator.php#L104

but - not going to block approval on this.

**Comment by cperves** [comment]
Yes it returns the url of the create image, stored in Moodle
entry dataImagUrl -> out Url

**Comment by danmarsden** [comment]
right - so a url is just text and doesn't need to be PARAM_RAW - it's probably safe as PARAM_TEXT instead.
