### ISSUE TITLE
not typical for styles.css to be listed in thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#6]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure/blob/MOODLE_401_STABLE/thirdpartylibs.xml#L11

that looks a bit strange and I can't see any chemdoodle css in the file at the moment?

**Comment by cperves** [comment]
Sorry I forgot to change that
