### ISSUE TITLE
installing plugin on a moodle 4.4dev site breaks the editor when cachejs is on.

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#7]
I'm testing this on a 4.4dev site and when I install this plugin, the tiny editor completely breaks and doesn't load anymore.

I get a bunch of errors in the console like:
require.min.js:5 Uncaught Error: Module name "canvas" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.min.js:5:1067)
    at Object.o [as require] (require.min.js:5:11053)
    at requirejs (require.min.js:5:14737)
    at first.js:5149:80

If I turn cachejs off - then it loads fine.

I'd guess that grunt needs to be run to rebuild the js but could be something else.

**Comment by cperves** [comment]
try this with #8 new 404 branch : 
- work with cachejs=false
- work also with cachejs=true

**Comment by cperves** [comment]
But with other dev parameters remove I have some troubles
seems to be due to $CFG->jsrev = -1; without this don't work
same trouble with 401 version
I'm going to find what's wrong with that

**Comment by cperves** [comment]
old files no more used
sorry it was dirty

**Comment by cperves** [comment]
PS : need purging all caches

**Comment by cperves** [comment]
@danmarsden new 404_devel and MOODLE_404_STABLE branches
