### ISSUE TITLE
inserting image throws error

### ISSUE THREAD

**Issue by danmarsden** [Laboratoire-de-Chemoinformatique/moodle-tiny_molstructure#8]
When trying to save an image I get the following error  (using Moodle 4.4dev for testing.)
Error code: generalexceptionmessage
* line 41 of /lib/editor/tiny/plugins/molstructure/classes/external/image_generator.php: Error thrown
* line 154 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by cperves** [comment]
No errors in 4.1, I'm going to work with a 4.4 dev version to correct that

**Comment by cperves** [comment]
I confirm it comes with 4.4dev moodle core branch

**Comment by cperves** [comment]
Class "external_api" not found dispirited of use external_api;
comes from new namespaces for external_api in modle 4.4;
need to make two version of plugin (I'll make a branch)
@danmarsden is it possible to validate this version for moodle 4.1, Il provide other version for moodle 4.4

**Comment by cperves** [comment]
new 404_devel branch
